 spring:
    application:
        name: queue-service
    server:
      port: ${PORT:8081}
    eureka:
      client:
        fetchRegistry: true
        registryFetchIntervalSeconds: 5
        serviceUrl:
          defaultZone: ${EUREKA_URI:http://192.168.100.37:8761/eureka}
      instance:
        preferIpAddress: true